- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  antagAdvantage: 2
  startingGear: ClerkGear
  icon: "JobIconClerk"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Justice
  - Security
  - Maintenance

- type: startingGear
  id: ClerkGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClerk
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: ClerkPDA
    ears: ClothingHeadsetJustice
  innerClothingSkirt: ClothingUniformJumpskirtClerk
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


